### ISSUE TITLE
Deprecated?

### ISSUE THREAD

**Issue by erikd** [jwiegley/find-conduit#11]
Hi John,

I notice that this has been marked as deprecated in Hackage?

    https://hackage.haskell.org/package/find-conduit

Do you mind if I take this over and maintain it?

**Comment by jwiegley** [comment]
Be my guest, Erik! There is a newer version based on pipes also, called
pipes-files. It also separates the traversal predicate logic into its own
package, hierarchy.

**Comment by erikd** [comment]
Thanks John. I did see that you had pipes version but the conduit version is more attractive to me as I'm already using conduit in this and other programs. I will probably take the chance to use the new predicate logic.
