### ISSUE TITLE
Repository is broken now.

### ISSUE THREAD

**Issue by junjihashimoto** [jwiegley/find-conduit#5]
Hi,

See https://github.com/jwiegley/find-conduit/blob/master/Data/Conduit/Find.hs#L532
leafOpt is not found.
Current repository is broken.

In addition to above syntax problem, this package has package dependecy problem.
As you can see https://github.com/jwiegley/find-conduit/pull/4,
MonadMask is not defined when exceptions is lower than 0.6.
MonadBaseControl does not work(build error is happend) when monad-contol is higher than 0.3.

Could you fix it ?

**Comment by junjihashimoto** [comment]
https://github.com/jwiegley/find-conduit/pull/6
Add support for monad-control-1 and exceptions-0.6.
Could you merge this?

If you are busy and no time, I can upload this.
https://hackage.haskell.org/package/find-conduit/maintainers/

**Comment by jwiegley** [comment]
Until this is fixed, does disabling leaf optimization work for you?

**Comment by junjihashimoto** [comment]
Thank you for quick response and merging  https://github.com/jwiegley/find-conduit/pull/6

Disabling leaf optimization is OK.
I am glad if you add its flag.

**Comment by junjihashimoto** [comment]
I have made this https://github.com/jwiegley/find-conduit/pull/7 for adding leafopt-flag.
Could you check this?
