### ISSUE TITLE
Failed to install find-conduit-0.4.3 (Manjaro)

### ISSUE THREAD

**Issue by xged** [jwiegley/find-conduit#9]
...
    Downloading find-conduit-0.4.3...
    Configuring find-conduit-0.4.3...
    Building find-conduit-0.4.3...
    Failed to install find-conduit-0.4.3
    Build log ( /home/xged/.cabal/logs/find-conduit-0.4.3.log ):
    Configuring find-conduit-0.4.3...
    Building find-conduit-0.4.3...
    Preprocessing library find-conduit-0.4.3...
    [1 of 2] Compiling Data.Cond        ( Data/Cond.hs, dist/build/Data/Cond.o )
    [2 of 2] Compiling Data.Conduit.Find ( Data/Conduit/Find.hs, dist/build/Data/Conduit/Find.o )
    In-place registering find-conduit-0.4.3...
    Preprocessing executable 'find-hs' for find-conduit-0.4.3...
    [1 of 1] Compiling Main             ( test/find-hs.hs, dist/build/find-hs/find-hs-tmp/Main.o )

    test/find-hs.hs:19:44:
        Couldn't match type ‘Filesystem.Path.CurrentOS.FilePath’
                    with ‘[Char]’
        Expected type: Prelude.FilePath
        Actual type: Filesystem.Path.CurrentOS.FilePath
        In the second argument of ‘sourceDirectoryDeep’, namely
        ‘(decodeString dir)’
        In the first argument of ‘(=$)’, namely
        ‘sourceDirectoryDeep False (decodeString dir)’

    test/find-hs.hs:20:56:
        Couldn't match type ‘[Char]’
                    with ‘Filesystem.Path.CurrentOS.FilePath’
        Expected type: Prelude.FilePath -> [Char]
        Actual type: Filesystem.Path.CurrentOS.FilePath -> String
        In the second argument of ‘(.)’, namely ‘encodeString’
        In the first argument of ‘filterC’, namely
        ‘((".hs" `isSuffixOf`) . encodeString)’

    test/find-hs.hs:21:52:
        Couldn't match type ‘[Char]’
                    with ‘Filesystem.Path.CurrentOS.FilePath’
        Expected type: Prelude.FilePath -> String
        Actual type: Filesystem.Path.CurrentOS.FilePath -> String
        In the second argument of ‘(.)’, namely ‘encodeString’
        In the second argument of ‘(.)’, namely ‘putStrLn . encodeString’
    cabal: Error: some packages failed to install:
    find-conduit-0.4.3 failed during the building phase. The exception was:
    ExitFailure 1

**Comment by jwiegley** [comment]
0.4.4 uploaded to Hackage.  Thanks for the heads up!
